In [2]:
import matplotlib.pyplot as plt
import numpy as np

In [3]:
nums_1d = np.ones((3), dtype = np.int8)
nums_1d

array([1, 1, 1], dtype=int8)

In [4]:
nums_2d = np.ones((3, 4), dtype = np.int8)
nums_2d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [5]:
nums_3d = np.ones((2, 3, 4), dtype = np.int8)
nums_3d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int8)

In [9]:
array_nums = np.array([3,4])
array_nums

array([3, 4])

In [10]:
array_nums * 2

array([6, 8])

In [13]:
array_nums_more = np.array([10,20])
array_nums_more

array([10, 20])

In [14]:
array_nums * array_nums_more

array([30, 80])

In [9]:
array_nums + array_nums_more

array([13, 24])

In [10]:
array_nums - array_nums_more


array([ -7, -16])

In [11]:
array_nums / array_nums_more

array([0.3, 0.2])

In [15]:
np.ndarray((2,4), np.int8) # garbage data

array([[10,  0,  0,  0],
       [ 0,  0,  0,  0]], dtype=int8)

In [16]:
from numpy import random
rands = np.random.randn(2,4) * 100 # random

In [17]:
rands.astype('int8')

array([[ 81,  31, -78, -17],
       [ 57, -37, -91, -48]], dtype=int8)

In [15]:
#np.save("rands.npy", rands)

In [18]:
for i in rands:
    print(i)

[-175.12218189   31.7941686   -78.02270962  -17.54362567]
[ 57.9988175  219.63334377 -91.56250195 -48.0226857 ]
