In [1]:
import numpy as np

In [4]:
x = np.array([3, 17, 14, 23, 2, 4, 6, 8, 1, 2, 16, 0])
np.clip(x, 2, 5)

array([3, 5, 5, 5, 2, 4, 5, 5, 2, 2, 5, 2])

In [5]:
# Random integers
array = np.random.randint(20, size=12)

In [6]:
#  Divide by 2 and check if remainder is 1
cond = np.mod(array, 2) == 1

In [7]:
# Use extract to get the values
np.extract(cond, array)

array([15, 17,  1,  5, 15,  5,  5,  5])

In [8]:
# Apply condition on extract directly
np.extract(((array < 3) | (array > 15)), array)

array([17,  0,  1,  2])

In [9]:
a = np.array([1, 5, 6, 8, 1, 7, 3, 6, 9])
print("50th Percentile of a, axis = 0 : ",
      np.percentile(a, 50, axis=0))

b = np.array([[10, 7, 4], [3, 2, 1]])
print("30th Percentile of b, axis = 0 : ", np.percentile(b, 30, axis=0))

50th Percentile of a, axis = 0 :  6.0
30th Percentile of b, axis = 0 :  [5.1 3.5 1.9]


In [18]:
import pandas as pd

In [10]:
# create a dataframe
dframe = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                      index=['India', 'USA', 'China', 'Russia'])


In [11]:
dframe

b         d         e
India   0.632033 -1.604109  0.080530
USA    -0.138018 -0.401056  1.001444
China   0.004199  1.278782 -0.348938
Russia -1.889652  1.378532 -0.752071

In [12]:
#compute a formatted string from each floating point value in frame
changefn = lambda x: '%.2f' % x
# Make changes element-wise
dframe['d'].map(changefn)

India     -1.60
USA       -0.40
China      1.28
Russia     1.38
Name: d, dtype: object

In [13]:
# max minus mix lambda fn
fn = lambda x: x.max() - x.min()
# Apply this on dframe that we've just created above
dframe.apply(fn)

b    2.521685
d    2.982640
e    1.753515
dtype: float64

In [14]:
# creating sample series
data = pd.Series(['India', 'Pakistan', 'China', 'Mongolia'])

In [15]:
# Assigning issue that we face
data1 = data
# Change a value
data1[0] = 'USA'
# Also changes value in old dataframe
data

0         USA
1    Pakistan
2       China
3    Mongolia
dtype: object

In [16]:
# To prevent that, we use
# creating copy of series
new = data.copy()
# assigning new values
new[1] = 'Changed value'
# printing data
print(new)
print(data)

0              USA
1    Changed value
2            China
3         Mongolia
dtype: object
0         USA
1    Pakistan
2       China
3    Mongolia
dtype: object


In [17]:
# Create a sample dataframe
school = pd.DataFrame({'A': ['Jay', 'Usher', 'Nicky', 'Romero', 'Will'],
                       'B': ['Masters', 'Graduate', 'Graduate', 'Masters',
                             'Graduate'],
                       'C': [26, 22, 20, 23, 24]})
school

A         B   C
0     Jay   Masters  26
1   Usher  Graduate  22
2   Nicky  Graduate  20
3  Romero   Masters  23
4    Will  Graduate  24

In [18]:
# Lets create a pivot table to segregate students based on age and course
table = pd.pivot_table(school, values='A', index=['B', 'C'],
                       columns=['B'], aggfunc=np.sum,
                       fill_value="Not Available")

table

B                 Graduate        Masters
B        C                               
Graduate 20          Nicky  Not Available
         22          Usher  Not Available
         24           Will  Not Available
Masters  23  Not Available         Romero
         26  Not Available            Jay

In [ ]:
# Random integers
array = np.random.randint(20, size=12)
array



In [ ]:
#  Divide by 2 and check if remainder is 1
cond = np.mod(array, 2) == 1
cond

In [ ]:
# Use extract to get the values
np.extract(cond, array)

In [ ]:

# Apply condition on extract directly
np.extract(((array < 3) | (array > 15)), array)

In [19]:
array1 = np.array([0.12, 0.17, 0.24, 0.29])
array2 = np.array([0.13, 0.19, 0.26, 0.31])
# with a tolerance of 0.1, it should return False:
np.allclose(array1, array2, 0.1)


False

In [20]:
# with a tolerance of 0.2, it should return True:
np.allclose(array1, array2, 0.2)

True

In [21]:
y = np.array([1, 5, 6, 8, 1, 7, 3, 6, 9])
# Where y is greater than 5, returns index position
np.where(y > 5)
# First will replace the values that match the condition,


(array([2, 3, 5, 7, 8]),)

In [22]:
# second will replace the values that does not
np.where(y > 5, "Hit", "Miss")

array(['Miss', 'Miss', 'Hit', 'Hit', 'Miss', 'Hit', 'Miss', 'Hit', 'Hit'],
      dtype='<U4')

In [ ]:
a = np.array([1, 5, 6, 8, 1, 7, 3, 6, 9])
print("50th Percentile of a, axis = 0 : ",
      np.percentile(a, 50, axis=0))
b = np.array([[10, 7, 4], [3, 2, 1]])
print("30th Percentile of b, axis = 0 : ",
      np.percentile(b, 30, axis=0))